name: flutter_tests
description: The Flutter project for different tests.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  http_proxy: ^1.2.2
  music_visualizer: ^1.0.4
  simple_animations: ^5.0.2
  uni_links: ^0.5.1
  vector_math: ^2.1.4
  webview_flutter: ^4.8.0
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.4

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
